# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo apt-get install pdftk
            sudo pip install pytest
      - run:
          name: run tests
          command: |
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml test.py
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
